(ns slides.web
  (:require [cljs.reader :as reader]
            [clojure.string :as str]
            [slides.model :as model]))

(def emu-per-inch 914400)
(def storage-key "kotoba-lang/slides.deck")
(def app-state
  (atom {:deck nil
         :selected-slide 0
         :selected-shape nil
         :mode :visual
         :error nil}))

(def sample-deck
  (-> (model/deck "web-deck"
                  {:slides/title "Web generated deck"
                   :slides/width 10
                   :slides/height 5.625})
      (model/add-slide
       (-> (model/slide "slide-1" {:slides/title "EDN to PPTX"})
           (model/add-shape
            (model/text-box "title" "EDN to PPTX"
                            {:slides/x 0.8 :slides/y 0.7 :slides/w 8.4 :slides/h 0.8
                             :slides/font-size 38}))
           (model/add-shape
            (model/text-box "body" "Generated by kotoba-lang/slides in CLJS"
                            {:slides/x 0.8 :slides/y 1.7 :slides/w 8.4 :slides/h 0.7
                             :slides/font-size 22}))
           (model/add-shape
            (model/rect "panel" {:slides/x 0.8 :slides/y 3.0 :slides/w 8.4 :slides/h 1.2}))))
      (model/add-slide
       (-> (model/slide "slide-2" {:slides/title "Pure data"})
           (model/add-shape
            (model/text-box "title" "Pure data deck model"
                            {:slides/x 0.8 :slides/y 0.8 :slides/w 8.4 :slides/h 0.8
                             :slides/font-size 34}))
           (model/add-shape
            (model/text-box "body" "Decks, slides, and shapes are EDN maps."
                            {:slides/x 0.8 :slides/y 1.8 :slides/w 8.4 :slides/h 0.7
                             :slides/font-size 22}))))))

(defn $ [id]
  (.getElementById js/document id))

(defn q [sel]
  (.querySelector js/document sel))

(defn escape-html [x]
  (-> (str (or x ""))
      (str/replace "&" "&amp;")
      (str/replace "<" "&lt;")
      (str/replace ">" "&gt;")
      (str/replace "\"" "&quot;")))

(defn valid-hex [x fallback]
  (let [s (-> (or x fallback) str (str/replace #"^#" "") str/upper-case)]
    (if (re-matches #"[0-9A-F]{6}" s) s fallback)))

(defn numeric [x fallback]
  (if (number? x) x fallback))

(defn positive [x fallback]
  (if (and (number? x) (pos? x)) x fallback))

(defn deck []
  (:deck @app-state))

(defn slides []
  (vec (:slides/slides (deck))))

(defn selected-slide-index []
  (let [idx (:selected-slide @app-state)
        max-idx (max 0 (dec (count (slides))))]
    (min max-idx (max 0 idx))))

(defn selected-slide []
  (get (slides) (selected-slide-index)))

(defn selected-shape-index []
  (:selected-shape @app-state))

(defn selected-shape []
  (when-let [idx (selected-shape-index)]
    (get (:slides/shapes (selected-slide)) idx)))

(defn replace-slide [idx f]
  (swap! app-state update-in [:deck :slides/slides]
         (fn [xs] (vec (map-indexed (fn [i x] (if (= i idx) (f x) x)) xs)))))

(defn replace-shape [slide-idx shape-idx f]
  (replace-slide slide-idx
                 (fn [slide]
                   (update slide :slides/shapes
                           (fn [xs]
                             (vec (map-indexed (fn [i x] (if (= i shape-idx) (f x) x)) xs)))))))

(defn save! []
  (when-let [d (deck)]
    (.setItem js/localStorage storage-key (pr-str d))))

(defn load-deck []
  (try
    (if-let [raw (.getItem js/localStorage storage-key)]
      (reader/read-string raw)
      sample-deck)
    (catch :default _
      sample-deck)))

(defn download! [name mime content]
  (let [blob (js/Blob. #js [content] #js {:type mime})
        url (.createObjectURL js/URL blob)
        a (.createElement js/document "a")]
    (set! (.-href a) url)
    (set! (.-download a) name)
    (.click a)
    (js/setTimeout #(.revokeObjectURL js/URL url) 1000)))

(defn u8 [xs]
  (js/Uint8Array. (clj->js xs)))

(defn u16 [n]
  [(bit-and n 255) (bit-and (bit-shift-right n 8) 255)])

(defn u32 [n]
  [(bit-and n 255)
   (bit-and (bit-shift-right n 8) 255)
   (bit-and (bit-shift-right n 16) 255)
   (bit-and (bit-shift-right n 24) 255)])

(def crc-table
  (delay
    (vec
     (for [n (range 256)]
       (loop [c n k 0]
         (if (= k 8)
           c
           (recur (if (pos? (bit-and c 1))
                    (bit-xor 0xEDB88320 (unsigned-bit-shift-right c 1))
                    (unsigned-bit-shift-right c 1))
                  (inc k))))))))

(defn crc32 [bytes]
  (loop [c 0xFFFFFFFF
         i 0]
    (if (= i (.-length bytes))
      (bit-and (bit-not c) 0xFFFFFFFF)
      (recur (bit-xor (get @crc-table (bit-and (bit-xor c (aget bytes i)) 255))
                      (unsigned-bit-shift-right c 8))
             (inc i)))))

(def encoder (js/TextEncoder.))

(defn encode [s]
  (.encode encoder (str s)))

(defn byte-length [chunks]
  (reduce + 0 (map #(.-length %) chunks)))

(defn zip-blob [files]
  (let [chunks (array)
        central (array)
        offset (atom 0)]
    (doseq [[name text] files]
      (let [data (encode text)
            name-bytes (encode name)
            crc (crc32 data)
            local (u8 (concat [0x50 0x4b 3 4 20 0 0 0 0 0 0 0 0 0]
                              (u32 crc) (u32 (.-length data)) (u32 (.-length data))
                              (u16 (.-length name-bytes)) [0 0]))
            dir (u8 (concat [0x50 0x4b 1 2 20 0 20 0 0 0 0 0 0 0 0 0]
                            (u32 crc) (u32 (.-length data)) (u32 (.-length data))
                            (u16 (.-length name-bytes)) [0 0 0 0 0 0 0 0 0 0 0]
                            (u32 @offset)))]
        (.push chunks local name-bytes data)
        (.push central dir name-bytes)
        (swap! offset + (.-length local) (.-length name-bytes) (.-length data))))
    (let [central-size (byte-length (array-seq central))
          end (u8 (concat [0x50 0x4b 5 6 0 0 0 0]
                          (u16 (count files)) (u16 (count files))
                          (u32 central-size) (u32 @offset) [0 0]))]
      (js/Blob. (clj->js (concat (array-seq chunks) (array-seq central) [end]))
                #js {:type "application/vnd.openxmlformats-officedocument.presentationml.presentation"}))))

(defn emu [inches]
  (js/Math.round (* emu-per-inch (numeric inches 0))))

(defn xml [x]
  (-> (escape-html x)
      (str/replace "'" "&apos;")))

(defn content-types [slide-count]
  (str "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
       "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">"
       "<Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>"
       "<Default Extension=\"xml\" ContentType=\"application/xml\"/>"
       "<Override PartName=\"/docProps/app.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.extended-properties+xml\"/>"
       "<Override PartName=\"/docProps/core.xml\" ContentType=\"application/vnd.openxmlformats-package.core-properties+xml\"/>"
       "<Override PartName=\"/ppt/presentation.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml\"/>"
       "<Override PartName=\"/ppt/slideMasters/slideMaster1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml\"/>"
       "<Override PartName=\"/ppt/slideLayouts/slideLayout1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml\"/>"
       "<Override PartName=\"/ppt/theme/theme1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.theme+xml\"/>"
       (apply str
              (for [idx (range 1 (inc slide-count))]
                (str "<Override PartName=\"/ppt/slides/slide" idx ".xml\" "
                     "ContentType=\"application/vnd.openxmlformats-officedocument.presentationml.slide+xml\"/>")))
       "</Types>"))

(def root-rels
  "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"ppt/presentation.xml\"/><Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties\" Target=\"docProps/core.xml\"/><Relationship Id=\"rId3\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties\" Target=\"docProps/app.xml\"/></Relationships>")

(defn core-props [d]
  (str "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
       "<cp:coreProperties xmlns:cp=\"http://schemas.openxmlformats.org/package/2006/metadata/core-properties\" xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" xmlns:dcmitype=\"http://purl.org/dc/dcmitype/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">"
       "<dc:title>" (xml (:slides/title d (:slides/id d "slides"))) "</dc:title>"
       "<dc:creator>kotoba-lang/slides</dc:creator></cp:coreProperties>"))

(defn app-props [slide-count]
  (str "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
       "<Properties xmlns=\"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties\" xmlns:vt=\"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes\">"
       "<Application>kotoba-lang/slides</Application><PresentationFormat>On-screen Show (16:9)</PresentationFormat><Slides>"
       slide-count "</Slides></Properties>"))

(defn presentation [slide-count width height]
  (str "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
       "<p:presentation xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\" xmlns:p=\"http://schemas.openxmlformats.org/presentationml/2006/main\">"
       "<p:sldMasterIdLst><p:sldMasterId id=\"2147483648\" r:id=\"rId1\"/></p:sldMasterIdLst><p:sldIdLst>"
       (apply str (for [idx (range 1 (inc slide-count))]
                    (str "<p:sldId id=\"" (+ 255 idx) "\" r:id=\"rId" (inc idx) "\"/>")))
       "</p:sldIdLst><p:sldSz cx=\"" (emu width) "\" cy=\"" (emu height) "\" type=\"wide\"/>"
       "<p:notesSz cx=\"6858000\" cy=\"9144000\"/></p:presentation>"))

(defn presentation-rels [slide-count]
  (str "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
       "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">"
       "<Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster\" Target=\"slideMasters/slideMaster1.xml\"/>"
       (apply str (for [idx (range 1 (inc slide-count))]
                    (str "<Relationship Id=\"rId" (inc idx) "\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide\" Target=\"slides/slide" idx ".xml\"/>")))
       "</Relationships>"))

(def theme-xml
  "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><a:theme xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\" name=\"kotoba\"><a:themeElements><a:clrScheme name=\"kotoba\"><a:dk1><a:srgbClr val=\"17202A\"/></a:dk1><a:lt1><a:srgbClr val=\"FFFFFF\"/></a:lt1><a:dk2><a:srgbClr val=\"334155\"/></a:dk2><a:lt2><a:srgbClr val=\"F7F8FB\"/></a:lt2><a:accent1><a:srgbClr val=\"496B9A\"/></a:accent1><a:accent2><a:srgbClr val=\"7C9A4B\"/></a:accent2><a:accent3><a:srgbClr val=\"B46A55\"/></a:accent3><a:accent4><a:srgbClr val=\"5C6F7E\"/></a:accent4><a:accent5><a:srgbClr val=\"8A6F3D\"/></a:accent5><a:accent6><a:srgbClr val=\"6A5A8E\"/></a:accent6><a:hlink><a:srgbClr val=\"315D8C\"/></a:hlink><a:folHlink><a:srgbClr val=\"6A5A8E\"/></a:folHlink></a:clrScheme><a:fontScheme name=\"kotoba\"><a:majorFont><a:latin typeface=\"Aptos Display\"/></a:majorFont><a:minorFont><a:latin typeface=\"Aptos\"/></a:minorFont></a:fontScheme><a:fmtScheme name=\"kotoba\"><a:fillStyleLst><a:solidFill><a:schemeClr val=\"phClr\"/></a:solidFill></a:fillStyleLst><a:lnStyleLst><a:ln w=\"6350\"><a:solidFill><a:schemeClr val=\"phClr\"/></a:solidFill></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:schemeClr val=\"phClr\"/></a:solidFill></a:bgFillStyleLst></a:fmtScheme></a:themeElements></a:theme>")

(def slide-master
  "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><p:sldMaster xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\" xmlns:p=\"http://schemas.openxmlformats.org/presentationml/2006/main\"><p:cSld><p:bg><p:bgPr><a:solidFill><a:srgbClr val=\"FFFFFF\"/></a:solidFill></p:bgPr></p:bg><p:spTree><p:nvGrpSpPr><p:cNvPr id=\"1\" name=\"\"/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x=\"0\" y=\"0\"/><a:ext cx=\"0\" cy=\"0\"/><a:chOff x=\"0\" y=\"0\"/><a:chExt cx=\"0\" cy=\"0\"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMap accent1=\"accent1\" accent2=\"accent2\" accent3=\"accent3\" accent4=\"accent4\" accent5=\"accent5\" accent6=\"accent6\" bg1=\"lt1\" bg2=\"lt2\" folHlink=\"folHlink\" hlink=\"hlink\" tx1=\"dk1\" tx2=\"dk2\"/><p:sldLayoutIdLst><p:sldLayoutId id=\"2147483649\" r:id=\"rId1\"/></p:sldLayoutIdLst><p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles></p:sldMaster>")

(def slide-master-rels
  "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout\" Target=\"../slideLayouts/slideLayout1.xml\"/><Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme\" Target=\"../theme/theme1.xml\"/></Relationships>")

(def slide-layout
  "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><p:sldLayout xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\" xmlns:p=\"http://schemas.openxmlformats.org/presentationml/2006/main\" type=\"blank\" preserve=\"1\"><p:cSld name=\"Blank\"><p:spTree><p:nvGrpSpPr><p:cNvPr id=\"1\" name=\"\"/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x=\"0\" y=\"0\"/><a:ext cx=\"0\" cy=\"0\"/><a:chOff x=\"0\" y=\"0\"/><a:chExt cx=\"0\" cy=\"0\"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>")

(def slide-layout-rels
  "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster\" Target=\"../slideMasters/slideMaster1.xml\"/></Relationships>")

(def slide-rels
  "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?><Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout\" Target=\"../slideLayouts/slideLayout1.xml\"/></Relationships>")

(defn shape-xfrm [{:slides/keys [x y w h]}]
  (str "<a:xfrm><a:off x=\"" (emu (numeric x 0)) "\" y=\"" (emu (numeric y 0)) "\"/>"
       "<a:ext cx=\"" (emu (positive w 1)) "\" cy=\"" (emu (positive h 1)) "\"/></a:xfrm>"))

(defn text-shape [idx {:slides/keys [id text font-size color] :as shape}]
  (str "<p:sp><p:nvSpPr><p:cNvPr id=\"" (+ 10 idx) "\" name=\"" (xml (or id (str "Text " idx))) "\"/>"
       "<p:cNvSpPr txBox=\"1\"/><p:nvPr/></p:nvSpPr>"
       "<p:spPr>" (shape-xfrm shape) "<a:prstGeom prst=\"rect\"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr>"
       "<p:txBody><a:bodyPr wrap=\"square\"/><a:lstStyle/><a:p><a:r><a:rPr lang=\"en-US\" sz=\""
       (* 100 (long (positive font-size 24))) "\"><a:solidFill><a:srgbClr val=\""
       (valid-hex color "17202A") "\"/></a:solidFill></a:rPr><a:t>" (xml text) "</a:t></a:r></a:p></p:txBody></p:sp>"))

(defn rect-shape [idx {:slides/keys [id fill line] :as shape}]
  (str "<p:sp><p:nvSpPr><p:cNvPr id=\"" (+ 10 idx) "\" name=\"" (xml (or id (str "Rect " idx))) "\"/>"
       "<p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr>" (shape-xfrm shape)
       "<a:prstGeom prst=\"rect\"><a:avLst/></a:prstGeom><a:solidFill><a:srgbClr val=\""
       (valid-hex fill "EAF0F8") "\"/></a:solidFill><a:ln w=\"12700\"><a:solidFill><a:srgbClr val=\""
       (valid-hex line "496B9A") "\"/></a:solidFill></a:ln></p:spPr></p:sp>"))

(defn render-ppt-shape [idx shape]
  (case (:slides/shape shape)
    :rect (rect-shape idx shape)
    :text (text-shape idx shape)
    (text-shape idx (assoc shape :slides/text (or (:slides/text shape) (:slides/title shape) "")))))

(defn slide-xml [slide]
  (str "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>"
       "<p:sld xmlns:a=\"http://schemas.openxmlformats.org/drawingml/2006/main\" xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\" xmlns:p=\"http://schemas.openxmlformats.org/presentationml/2006/main\">"
       "<p:cSld><p:bg><p:bgPr><a:solidFill><a:srgbClr val=\"FFFFFF\"/></a:solidFill></p:bgPr></p:bg><p:spTree>"
       "<p:nvGrpSpPr><p:cNvPr id=\"1\" name=\"\"/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x=\"0\" y=\"0\"/><a:ext cx=\"0\" cy=\"0\"/><a:chOff x=\"0\" y=\"0\"/><a:chExt cx=\"0\" cy=\"0\"/></a:xfrm></p:grpSpPr>"
       (if (seq (:slides/shapes slide))
         (apply str (map-indexed render-ppt-shape (:slides/shapes slide)))
         (text-shape 0 {:slides/id "title" :slides/text (:slides/title slide) :slides/x 0.8 :slides/y 0.8 :slides/w 8.4 :slides/h 1.0 :slides/font-size 32}))
       "</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>"))

(defn deck-slides [d]
  (let [xs (:slides/slides d)]
    (if (seq xs)
      (vec xs)
      [{:slides/id "slide-1" :slides/title (:slides/title d (:slides/id d "Slides")) :slides/shapes []}])))

(defn pptx-blob [d]
  (let [ss (deck-slides d)
        width (positive (:slides/width d) 10)
        height (positive (:slides/height d) 5.625)
        files (concat
               [["[Content_Types].xml" (content-types (count ss))]
                ["_rels/.rels" root-rels]
                ["docProps/core.xml" (core-props d)]
                ["docProps/app.xml" (app-props (count ss))]
                ["ppt/presentation.xml" (presentation (count ss) width height)]
                ["ppt/_rels/presentation.xml.rels" (presentation-rels (count ss))]
                ["ppt/theme/theme1.xml" theme-xml]
                ["ppt/slideMasters/slideMaster1.xml" slide-master]
                ["ppt/slideMasters/_rels/slideMaster1.xml.rels" slide-master-rels]
                ["ppt/slideLayouts/slideLayout1.xml" slide-layout]
                ["ppt/slideLayouts/_rels/slideLayout1.xml.rels" slide-layout-rels]]
               (mapcat (fn [idx slide]
                         (let [n (inc idx)]
                           [[(str "ppt/slides/slide" n ".xml") (slide-xml slide)]
                            [(str "ppt/slides/_rels/slide" n ".xml.rels") slide-rels]]))
                       (range) ss))]
    (zip-blob (vec files))))

(defn shape-style [deck-width deck-height shape selected?]
  (let [x (/ (* 100 (numeric (:slides/x shape) 0)) deck-width)
        y (/ (* 100 (numeric (:slides/y shape) 0)) deck-height)
        w (/ (* 100 (positive (:slides/w shape) 1)) deck-width)
        h (/ (* 100 (positive (:slides/h shape) 1)) deck-height)]
    (str "left:" x "%;top:" y "%;width:" w "%;height:" h "%;"
         "font-size:" (positive (:slides/font-size shape) 24) "px;"
         "color:#" (valid-hex (:slides/color shape) "17202A") ";"
         (when selected? "outline:2px solid #111827;outline-offset:2px;"))))

(defn slide-thumb [idx slide]
  (str "<button class=\"thumb" (when (= idx (selected-slide-index)) " active") "\" data-slide=\"" idx "\">"
       "<span>" (escape-html (:slides/title slide (:slides/id slide))) "</span>"
       "<small>" (inc idx) "</small></button>"))

(defn shape-node [idx shape]
  (let [d (deck)
        width (positive (:slides/width d) 10)
        height (positive (:slides/height d) 5.625)
        selected? (= idx (selected-shape-index))
        base (str "shape " (name (:slides/shape shape :text)) (when selected? " selected"))]
    (case (:slides/shape shape)
      :rect
      (str "<button class=\"" base "\" data-shape=\"" idx "\" style=\""
           (shape-style width height shape selected?) "background:#" (valid-hex (:slides/fill shape) "EAF0F8")
           ";border-color:#" (valid-hex (:slides/line shape) "496B9A") ";\"></button>")
      (str "<button class=\"" base "\" data-shape=\"" idx "\" style=\"" (shape-style width height shape selected?) "\">"
           (escape-html (:slides/text shape "")) "</button>"))))

(defn property-input [label id value attrs]
  (str "<label><span>" label "</span><input id=\"" id "\" value=\"" (escape-html value) "\" " attrs "></label>"))

(defn selected-properties []
  (if-let [shape (selected-shape)]
    (str "<div class=\"panel-title\">Shape</div>"
         (property-input "ID" "shape-id" (:slides/id shape "") "")
         "<label><span>Kind</span><select id=\"shape-kind\"><option value=\"text\"" (when (= :text (:slides/shape shape)) " selected") ">Text</option><option value=\"rect\"" (when (= :rect (:slides/shape shape)) " selected") ">Rect</option></select></label>"
         (when (not= :rect (:slides/shape shape))
           (str "<label><span>Text</span><textarea id=\"shape-text\">" (escape-html (:slides/text shape "")) "</textarea></label>"))
         "<div class=\"grid2\">"
         (property-input "X" "shape-x" (:slides/x shape 0) "type=\"number\" step=\"0.1\"")
         (property-input "Y" "shape-y" (:slides/y shape 0) "type=\"number\" step=\"0.1\"")
         (property-input "W" "shape-w" (:slides/w shape 1) "type=\"number\" step=\"0.1\"")
         (property-input "H" "shape-h" (:slides/h shape 1) "type=\"number\" step=\"0.1\"")
         "</div>"
         (if (= :rect (:slides/shape shape))
           (str "<div class=\"grid2\">" (property-input "Fill" "shape-fill" (:slides/fill shape "EAF0F8") "")
                (property-input "Line" "shape-line" (:slides/line shape "496B9A") "") "</div>")
           (str "<div class=\"grid2\">" (property-input "Font" "shape-font-size" (:slides/font-size shape 24) "type=\"number\" step=\"1\"")
                (property-input "Color" "shape-color" (:slides/color shape "17202A") "") "</div>"))
         "<button id=\"delete-shape\" class=\"danger\">Delete Shape</button>")
    (let [slide (selected-slide)]
      (str "<div class=\"panel-title\">Slide</div>"
           (property-input "ID" "slide-id" (:slides/id slide "") "")
           (property-input "Title" "slide-title" (:slides/title slide "") "")
           "<button id=\"delete-slide\" class=\"danger\">Delete Slide</button>"))))

(defn render! []
  (let [d (deck)
        ss (slides)
        slide (selected-slide)
        width (positive (:slides/width d) 10)
        height (positive (:slides/height d) 5.625)]
    (set! (.-innerHTML ($ "slide-list")) (apply str (map-indexed slide-thumb ss)))
    (set! (.-innerHTML ($ "canvas-wrap"))
          (str "<div id=\"canvas\" class=\"canvas\" style=\"aspect-ratio:" width "/" height ";\">"
               (apply str (map-indexed shape-node (:slides/shapes slide)))
               "</div>"))
    (set! (.-innerHTML ($ "properties")) (selected-properties))
    (set! (.-value ($ "deck-edn")) (pr-str d))
    (set! (.-textContent ($ "status"))
          (str (count ss) " slides / " (count (:slides/shapes slide)) " shapes"))
    (set! (.-textContent ($ "error")) (or (:error @app-state) ""))
    (set! (.-hidden ($ "visual-pane")) (not= :visual (:mode @app-state)))
    (set! (.-hidden ($ "edn-pane")) (not= :edn (:mode @app-state)))))

(defn rerender-save! []
  (save!)
  (render!))

(defn parse-number [id fallback]
  (let [n (js/parseFloat (.-value ($ id)))]
    (if (js/isNaN n) fallback n)))

(defn update-shape-from-form! []
  (let [slide-idx (selected-slide-index)
        shape-idx (selected-shape-index)]
    (when (some? shape-idx)
      (replace-shape
       slide-idx shape-idx
       (fn [shape]
         (let [kind (keyword (.-value ($ "shape-kind")))
               base (assoc shape
                           :slides/id (.-value ($ "shape-id"))
                           :slides/shape kind
                           :slides/x (parse-number "shape-x" (:slides/x shape 0))
                           :slides/y (parse-number "shape-y" (:slides/y shape 0))
                           :slides/w (parse-number "shape-w" (:slides/w shape 1))
                           :slides/h (parse-number "shape-h" (:slides/h shape 1)))]
           (if (= kind :rect)
             (-> base
                 (assoc :slides/fill (.-value ($ "shape-fill"))
                        :slides/line (.-value ($ "shape-line")))
                 (dissoc :slides/text :slides/font-size :slides/color))
             (-> base
                 (assoc :slides/text (.-value ($ "shape-text"))
                        :slides/font-size (parse-number "shape-font-size" (:slides/font-size shape 24))
                        :slides/color (.-value ($ "shape-color")))
                 (dissoc :slides/fill :slides/line)))))))))

(defn update-slide-from-form! []
  (let [idx (selected-slide-index)]
    (replace-slide idx #(assoc % :slides/id (.-value ($ "slide-id"))
                                 :slides/title (.-value ($ "slide-title"))))))

(defn next-id [prefix xs]
  (str prefix "-" (inc (count xs))))

(defn add-slide! []
  (let [ss (slides)
        id (next-id "slide" ss)]
    (swap! app-state update-in [:deck :slides/slides] conj
           (-> (model/slide id {:slides/title (str "Slide " (inc (count ss)))})
               (model/add-shape (model/text-box "title" "New slide"
                                                {:slides/font-size 34}))))
    (swap! app-state assoc :selected-slide (count ss) :selected-shape nil)
    (rerender-save!)))

(defn duplicate-slide! []
  (let [idx (selected-slide-index)
        copy (assoc (selected-slide)
                    :slides/id (next-id "slide" (slides))
                    :slides/title (str (:slides/title (selected-slide) "Slide") " copy"))]
    (swap! app-state update-in [:deck :slides/slides]
           (fn [ss] (vec (concat (subvec (vec ss) 0 (inc idx)) [copy] (subvec (vec ss) (inc idx))))))
    (swap! app-state assoc :selected-slide (inc idx) :selected-shape nil)
    (rerender-save!)))

(defn delete-slide! []
  (when (> (count (slides)) 1)
    (let [idx (selected-slide-index)]
      (swap! app-state update-in [:deck :slides/slides]
             (fn [ss] (vec (concat (subvec (vec ss) 0 idx) (subvec (vec ss) (inc idx))))))
      (swap! app-state assoc :selected-slide (max 0 (dec idx)) :selected-shape nil)
      (rerender-save!))))

(defn add-shape! [kind]
  (let [idx (selected-slide-index)
        shapes (:slides/shapes (selected-slide))
        shape (if (= kind :rect)
                (model/rect (next-id "rect" shapes)
                            {:slides/x 1.0 :slides/y 2.8 :slides/w 4.0 :slides/h 1.2})
                (model/text-box (next-id "text" shapes) "Text"
                                {:slides/x 1.0 :slides/y 1.0 :slides/w 5.0 :slides/h 0.8
                                 :slides/font-size 28}))]
    (replace-slide idx #(update % :slides/shapes conj shape))
    (swap! app-state assoc :selected-shape (count shapes))
    (rerender-save!)))

(defn delete-shape! []
  (when-let [shape-idx (selected-shape-index)]
    (let [slide-idx (selected-slide-index)]
      (replace-slide slide-idx
                     #(update % :slides/shapes
                              (fn [xs] (vec (concat (subvec (vec xs) 0 shape-idx)
                                                    (subvec (vec xs) (inc shape-idx)))))))
      (swap! app-state assoc :selected-shape nil)
      (rerender-save!))))

(defn apply-edn! []
  (try
    (let [parsed (reader/read-string (.-value ($ "deck-edn")))]
      (swap! app-state assoc :deck parsed :selected-slide 0 :selected-shape nil :error nil :mode :visual)
      (rerender-save!))
    (catch :default e
      (swap! app-state assoc :error (.-message e))
      (render!))))

(defn import-edn! [file]
  (let [reader (js/FileReader.)]
    (set! (.-onload reader)
          (fn [event]
            (try
              (let [parsed (reader/read-string (.. event -target -result))]
                (swap! app-state assoc :deck parsed :selected-slide 0 :selected-shape nil :error nil)
                (rerender-save!))
              (catch :default e
                (swap! app-state assoc :error (.-message e))
                (render!)))))
    (.readAsText reader file)))

(defn install-events! []
  (.addEventListener js/document "click"
                     (fn [event]
                       (let [target (.-target event)]
                         (cond
                           (.closest target "#new-deck")
                           (do (swap! app-state assoc :deck sample-deck :selected-slide 0 :selected-shape nil :error nil)
                               (rerender-save!))

                           (.closest target "#add-slide") (add-slide!)
                           (.closest target "#duplicate-slide") (duplicate-slide!)
                           (.closest target "#add-text") (add-shape! :text)
                           (.closest target "#add-rect") (add-shape! :rect)
                           (.closest target "#delete-slide") (delete-slide!)
                           (.closest target "#delete-shape") (delete-shape!)

                           (.closest target "#download-edn")
                           (download! "deck.edn" "application/edn;charset=utf-8" (pr-str (deck)))

                           (.closest target "#download-pptx")
                           (let [blob (pptx-blob (deck))
                                 url (.createObjectURL js/URL blob)
                                 a (.createElement js/document "a")]
                             (set! (.-href a) url)
                             (set! (.-download a) "deck.pptx")
                             (.click a)
                             (js/setTimeout #(.revokeObjectURL js/URL url) 1000))

                           (.closest target "#apply-edn") (apply-edn!)

                           (.closest target "#mode-visual")
                           (do (swap! app-state assoc :mode :visual) (render!))

                           (.closest target "#mode-edn")
                           (do (swap! app-state assoc :mode :edn) (render!))

                           :else
                           (when-let [slide-button (.closest target "[data-slide]")]
                             (swap! app-state assoc
                                    :selected-slide (js/parseInt (.getAttribute slide-button "data-slide") 10)
                                    :selected-shape nil)
                             (render!)))
                         (when-let [shape-button (.closest target "[data-shape]")]
                           (.stopPropagation event)
                           (swap! app-state assoc :selected-shape (js/parseInt (.getAttribute shape-button "data-shape") 10))
                           (render!)))))
  (.addEventListener js/document "change"
                     (fn [event]
                       (let [target (.-target event)]
                         (cond
                           (= "edn-file" (.-id target))
                           (when-let [file (aget (.-files target) 0)]
                             (import-edn! file))

                           (.closest target "#properties")
                           (do (if (some? (selected-shape-index))
                                 (update-shape-from-form!)
                                 (update-slide-from-form!))
                               (rerender-save!))))))
  (.addEventListener js/document "input"
                     (fn [event]
                       (let [target (.-target event)]
                         (when (.closest target "#properties")
                           (if (some? (selected-shape-index))
                             (update-shape-from-form!)
                             (update-slide-from-form!))
                           (rerender-save!))))))

(defn init! []
  (swap! app-state assoc :deck (load-deck))
  (install-events!)
  (render!))

(set! (.-onload js/window) init!)
